//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNest.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeNest.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data..
        /// </summary>
        public static string CN_Error_1001 {
            get {
                return ResourceManager.GetString("CN_Error_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating!.
        /// </summary>
        public static string CN_Error_1002 {
            get {
                return ResourceManager.GetString("CN_Error_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already workspace has been created on the same name..
        /// </summary>
        public static string CN_Error_1003 {
            get {
                return ResourceManager.GetString("CN_Error_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated successfully..
        /// </summary>
        public static string CN_Success_1001 {
            get {
                return ResourceManager.GetString("CN_Success_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace created successfully..
        /// </summary>
        public static string CN_Success_1002 {
            get {
                return ResourceManager.GetString("CN_Success_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json.
        /// </summary>
        public static string CN_Type_001 {
            get {
                return ResourceManager.GetString("CN_Type_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript.
        /// </summary>
        public static string CN_Type_002 {
            get {
                return ResourceManager.GetString("CN_Type_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string CN_Type_003 {
            get {
                return ResourceManager.GetString("CN_Type_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string CN_Update_1001 {
            get {
                return ResourceManager.GetString("CN_Update_1001", resourceCulture);
            }
        }
    }
}
